# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewWindow(object):
    def setupUi(self, NewWindow):
        NewWindow.setObjectName("NewWindow")
        NewWindow.resize(900, 900)
        NewWindow.setMinimumSize(900,900)
        self.centralwidget = QtWidgets.QWidget(NewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(285, 0, 80, 50))
        self.pushButton.setObjectName("fish")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 50, 300,300))
        self.calendarWidget.setObjectName("calendarWidget")
        NewWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NewWindow)
        self.statusbar.setObjectName("statusbar")
        NewWindow.setStatusBar(self.statusbar)

        NewWindow.setWindowTitle('Window')
        self.pushButton.setText('create')
        self.label.setText('write')

        self.label_2=QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(400,400, 70,150)
        self.pushButton.clicked.connect(self.on_button_click)

        with open ('style.qss') as f:
            NewWindow.setStyleSheet(f.read())
        QtCore.QMetaObject.connectSlotsByName(NewWindow)

    def on_button_click(self):
        self.label_2.setText('surprise')




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewWindow = QtWidgets.QMainWindow()
    ui = Ui_NewWindow()
    ui.setupUi(NewWindow)
    NewWindow.show()
    sys.exit(app.exec_())
